packages:
  - curl
  - git

write_files:
  - path: /etc/environment
    owner: root:root
    permission: "0644"
    content: |
      PORT=8080
      DB_CONNECTION_STRING="mongodb://${user}:${password}@${hostname}:${port}/?ssl=true&sslCAFile=/etc/ssl/certs/docdb-conn.pem"
  - path: /etc/systemd/system/phoenix.service
    owner: root:root
    permission: "0644"
    content: |
      [Unit]
      Description=Phoenix Application
      [Service]
      # Start Service
      WorkingDirectory=/var/www/cloud-phoenix-kata
      ExecStart=/usr/bin/npm start
      RestartSec=10
      Restart=on-failure
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=nodejs-phoenix-application
      User=nobody
      Group=nobody
      Environment=PORT=8080
      Environment=DB_CONNECTION_STRING="mongodb://${user}:${password}@${hostname}:${port}/?ssl=true&sslCAFile=/etc/ssl/certs/docdb-conn.pem"
      [Install]
      WantedBy=multi-user.target
      


runcmd:
  - |
    echo
    source /etc/environment
    echo "*** install nodejs"
    curl -sL https://rpm.nodesource.com/setup_14.x | bash -
    yum -y install npm
    mkdir /var/www/
    cd /var/www
    git clone https://github.com/claranet-ch/cloud-phoenix-kata
    cd /var/www/cloud-phoenix-kata
    npm install
    echo "*** retrive ssl certificate for documentDB connection"
    curl -o /etc/ssl/certs/docdb-conn.pem https://truststore.pki.rds.amazonaws.com/eu-central-1/eu-central-1-bundle.pem
    chmod 644 /etc/ssl/certs/docdb-conn.pem


