packages:
  - curl
  - git

write_files:
  - path: /etc/environment
    owner: root:root
    permission: "0644"
    content: |
      PORT=8080
      DB_CONNECTION_STRING="mongodb://${user}:${password}@${hostname}:${port}/${database}}"
  - path: /etc/systemd/system/phoenix.service
    owner: root:root
    permission: "0644"
    content: |
      [Unit]
      Description=Phoenix Application
      [Service]
      # Start Service
      WorkingDirectory=/var/www/cloud-phoenix-kata
      ExecStart=/usr/bin/npm start
      RestartSec=10
      Restart=on-failure
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=nodejs-phoenix-application
      User=nobody
      Group=nobody
      Environment=PORT=8080
      Environment=DB_CONNECTION_STRING="mongodb://${user}:${password}@${hostname}:${port}/${database}}"
      [Install]
      WantedBy=multi-user.target
      


runcmd:
  - |
    echo
    touch ${user}
    touch ${password}
    echo "*** Setting environment variables globally"
    echo "*** TODO - set only for the user that launch application"
    source /etc/environment
    echo "*** install nodejs"
    curl -sL https://rpm.nodesource.com/setup_14.x | bash -
    yum -y install npm
    cd /root
    touch yes.txt
    cd /home/ec2-user
    touch 2.txt 
    mkdir /var/www/
    cd /var/www
    git clone https://github.com/claranet-ch/cloud-phoenix-kata
    cd /var/www/cloud-phoenix-kata
    npm install


